### ISSUE TITLE
event.getId() always returns 0

### ISSUE THREAD

**Issue by sdo91** [dvlopt/linux-gpio.java#1]
When I run the push buttons example, `event.getId()` always returns 0.
Any idea why that might be happening?
I'm running the code on an UP board, Ubuntu 16.04

I changed the device path and line numbers to match my board:
```
PATH_TO_DEVICE = "/dev/gpiochip4" ;
LINE_NUMBER_BUTTON_1 = 6 ;
LINE_NUMBER_BUTTON_2 = 5 ;
```

run output:
```
Starting push buttons...

Come on, press any button and keep pressin' ! Program will terminates after 15000 milliseconds of inactivity.

// when I push the 1st button (expected output: button 1)
1598314100861091495 button 0
1598314101203325508 button 0

// when I push the 2nd button (expected output: button 2)
1598314106373799169 button 0
1598314106500737447 button 0

Timeout, terminating program...
```

**Comment by helins** [comment]
Odd... I haven't done any GPIO progaming in a while but I have never encountered that. I have never experimented with a UP board but it should not be a problem. Did you experience any other problem ? I would expect it to break in more than one place if it had to.

**Comment by sdo91** [comment]
I didn't experience any other issues. The interrupt works fine, I just can't tell which button it comes from.

**Comment by helins** [comment]
Then I don't know, I'll try to have a look when I find time. I would not be that surprised if it turns out to be an issue with the environment. If you happen to try it with another board and still experience this issue, please re-open it :+1: 

Meanwhile, if you need interrupts for a project, a simple fix for your problem is to use one GPIO watcher per line. By doing so, you will be blocking one thread per line, but unless you have an obscene number of inputs, it won't make much of a difference.

What kernel version are you using, is it up-to-date ?
