### ISSUE TITLE
Override Gpio line consumer?

### ISSUE THREAD

**Issue by pratiklib16** [dvlopt/linux-gpio.java#3]
Hi, 
I'm using your library to detect button press connected to gpio lines on imx6 board running embedded linux (buildroot). When I call GpioEventHandle requestEvent() to register the handle I'm getting IO exception: `java.io.IOException: A requested line is already being used elsewhere`
I read in your javadoc that request can be handled by one instance at a time. Is there a way to newly register request handle and overriding consumer which is already using it by setting new one? (FYI I did getconsumer on gpio line and it shows "sysfs")

Thanks

**Comment by helins** [comment]
Is it just about `requestEvent`? Is everything else working fine?

**Comment by pi-r-p** [comment]
Hi,
You cannot use libgpiod and sysfs together.
Be careful not to use sysfs at all in your setup (/sys/class/gpio is deprecated).

- What is the output of gpiodetect and gpioinfo commands for the gpiochip and line you want ? It should be unused... otherwise you cannot use it with linux-gpio.java.
- Make sure users can access /dev/gpiochip*  ... For example, you can create a gpiod group, then create a udev rule to grant access to users belonging to this group:
```
sudo groupadd gpiod
sudo usermod -G gpiod user
sudo echo '# udev rules for gpio port access through libgpiod
SUBSYSTEM=="gpio", KERNEL=="gpiochip0", GROUP="gpiod", MODE="0660"' > /etc/udev/rules.d/60-gpiod.rules
```

**Comment by pratiklib16** [comment]
@pi-r-p thank you for the input. I changed the udev rule not to use sysfs for the gpio chip. Now it is working fine!

@helins Yes that was the only issue I faced but now it is resolved as @pi-r-p suggested. 

Thank you for your help!
